import UIKit

struct StringConstants {
    static let kLblShowMore: String = "Show More"
    static let k: String = ""
    static let kMsg1Of4Completed: String = "1 of 4 completed"
    static let kLblAddPlan: String = "Add Plan"
    static let kLblSearch: String = "Search"
    static let kMsgAmountHowLong: String = "Amount & How long?"
    static let kLbl2: String = "2"
    static let kLbl3: String = "3"
    static let kLblDays: String = "days"
    static let kLblDailyReview: String = "Daily Review"
    static let kMsgYourPlanForToday: String = "Your plan\nfor today"
    static let kLblOxycodone: String = "Oxycodone"
    static let kLblFoodPills: String = "Food & Pills"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblSkipped: String = "Skipped"
    static let kLbl30: String = "30"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblCompleted: String = "Completed"
    static let kLblNotification: String = "Notification"
    static let kLblKathryn: String = "Kathryn"
    static let kLbl1000Am: String = "10:00 AM"
    static let kLblHelloKathryn: String = "Hello,\nKathryn"
    static let kLblHello: String = "Hello,\n"
    static let kLblNaloxone: String = "Naloxone"
    static let kLblPillsName: String = "Pills name"
    static let kLbl0400Pm: String = "04:00 PM"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblPills: String = "pills"
    static let kLblBeforeEating: String = "Before Eating"
    static let kLblDone: String = "Done"
}
